version: "3"

services:
  productapi.db:
    image: postgres
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=L0calpaS5
      - POSTGRES_DB=products
    networks:
      - kafka_network

  productapi:
    image: product.api:${TAG:-latest}
    ports:
      - "80:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - AWS_ACCESS_KEY_ID=blah
      - AWS_SECRET_ACCESS_KEY=blah
      - AWS_REGION=ap-southeast-2
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - kafka_network
    depends_on:
      - productapi.db

networks:
  kafka_network:
    external: true